### For Linux users

   ####  https://www.how2shout.com/linux/how-to-install-rstudio-ubuntu-20-04-lts-linux/
   
   sudo apt update -qq
   
   sudo apt install --no-install-recommends software-properties-common dirmngr
   
   wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
   
   sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
   
   sudo apt install --no-install-recommends r-base
   
   sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
   
   bash -c "$(curl -L https://rstd.io/r-install)"
   
   cd /home/Downloads
   
   sudo apt install ./rstudio-*-amd64.deb
   
   R

install.packages('IRkernel')

### For Windows users

#### https://developers.refinitiv.com/en/article-catalog/article/setup-jupyter-notebook-r

Steps to setup Jupyter Notebook for R

1. Install R

https://cloud.r-project.org/index.html

2. Install Python

3. Install Jupyter Notebook

4. Install R kernel for Jupyter Notebook

You can install the IRkernel packages by running to the following command in an R console:

install.packages('IRkernel')

IRkernel::installspec(user = FALSE)

## Basic arithmetic operators and logical operators

In [1]:
10+25 #Addition

[1] 35

In [2]:
35-10 #Subtraction

[1] 25

In [3]:
30/4 #Division

[1] 7.5

In [4]:
25%%3 #Modulus(Remainder)

[1] 1

In [5]:
25%/%3 #Integer Division

[1] 8

In [8]:
10^3 #Square

[1] 1000

## How to use help in R?
#### R has a very good built-in help system. 
#### If you know which function you want help with simply use ?_______ with the function in the blank.
#### Ex:  ?hist

In [1]:
?ls

ls                    package:base                     R Documentation

_L_i_s_t _O_b_j_e_c_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     'ls' and 'objects' return a vector of character strings giving the
     names of the objects in the specified environment.  When invoked
     with no argument at the top level prompt, 'ls' shows what data
     sets and functions a user has defined.  When invoked with no
     argument inside a function, 'ls' returns the names of the
     function's local variables: this is useful in conjunction with
     'browser'.

_U_s_a_g_e:

     ls(name, pos = -1L, envir = as.environment(pos),
        all.names = FALSE, pattern, sorted = TRUE)
     objects(name, pos= -1L, envir = as.environment(pos),
             all.names = FALSE, pattern, sorted = TRUE)
     
_A_r_g_u_m_e_n_t_s:

    name: which environment to use in listing the available objects.
          Defaults to the _current_ environment.  Although called
          'name' for back compatibility, in fact this argument can
          specify the environment in any form; see the 'Details'
          section.

     pos: an alternative argument to 'name' for specifying the
          environment as a position in the search list.  Mostly there
          for back compatibility.

   envir: an alternative argument to 'name' for specifying the
          environment.  Mostly there for back compatibility.

all.names: a logical value.  If 'TRUE', all object names are returned.
          If 'FALSE', names which begin with a '.' are omitted.

 pattern: an optional regular expression.  Only names matching
          'pattern' are returned.  'glob2rx' can be used to convert
          wildcard patterns to regular expressions.

  sorted: logical indicating if the resulting 'character' should be
          sorted alphabetically.  Note that this is part of 'ls()' may
          take most of the time.

_D_e_t_a_i_l_s:

     The 'name' argument can specify the environment from which object
     names are taken in one of several forms: as an integer (the
     position in the 'search' list); as the character string name of an
     element in the search list; or as an explicit 'environment'
     (including using 'sys.frame' to access the currently active
     function calls).  By default, the environment of the call to 'ls'
     or 'objects' is used. The 'pos' and 'envir' arguments are an
     alternative way to specify an environment, but are primarily there
     for back compatibility.

     Note that the _order_ of strings for 'sorted = TRUE' is locale
     dependent, see 'Sys.getlocale'.  If 'sorted = FALSE' the order is
     arbitrary, depending if the environment is hashed, the order of
     insertion of objects, ....

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'glob2rx' for converting wildcard patterns to regular expressions.

     'ls.str' for a long listing based on 'str'.  'apropos' (or 'find')
     for finding objects in the whole search path; 'grep' for more
     details on 'regular expressions'; 'class', 'methods', etc., for
     object-oriented programming.

_E_x_a_m_p_l_e_s:

     .Ob <- 1
     ls(pattern = "O")
     ls(pattern= "O", all.names = TRUE)    # also shows ".[foo]"
     
     # shows an empty list because inside myfunc no variables are defined
     myfunc <- function() {ls()}
     myfunc()
     
     # define a local variable inside myfunc
     myfunc <- function() {y <- 1; ls()}
     myfunc()                # shows "y"

### To install or add new R packages

#### https://cran.r-project.org/web/packages/available_packages_by_name.html

In [11]:
install.packages("AGD")

Installing package into ‘/home/vivek/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gamlss.data’, ‘gamlss’, ‘gamlss.dist’




In [13]:
install.packages('AGD')

Installing package into ‘/home/vivek/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)



### To load the package

In [15]:
library(AGD)

### To see default packages on R

In [17]:
library()

Warning message in library():
“libraries ‘/usr/local/lib/R/site-library’, ‘/usr/lib/R/site-library’ contain no packages”


R packages available

Packages in library ‘/home/vivek/R/x86_64-pc-linux-gnu-library/4.2’:

AGD                     Analysis of Growth Data
base64enc               Tools for base64 encoding
cli                     Helpers for Developing Command Line Interfaces
colorspace              A Toolbox for Manipulating and Assessing Colors
                        and Palettes
crayon                  Colored Terminal Output
digest                  Create Compact Hash Digests of R Objects
evaluate                Parsing and Evaluation Tools that Provide More
                        Details than the Default
fansi                   ANSI Control Sequence Aware String Functions
farver                  High Performance Colour Space Manipulation
fastmap                 Fast Data Structures
gamlss                  Generalised Additive Models for Location Scale
                        and Shape
gamlss.data             Data for Generalised Additive Models for
                        Location Scale and Sha

### To see installed packages on R

In [19]:
installed.packages()

Package     LibPath                                       Version 
AGD         AGD         /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.39    
base64enc   base64enc   /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.1-3   
cli         cli         /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 3.4.1   
colorspace  colorspace  /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.0-3   
crayon      crayon      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.5.2   
digest      digest      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.6.29  
evaluate    evaluate    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.17    
fansi       fansi       /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.0.3   
farver      farver      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.1.1   
fastmap     fastmap     /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.1.0   
gamlss      gamlss      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 5.4-3   
gamlss.data gamlss.data /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 6.0-2   
gamlss.dist gamlss.dist /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 6.0-5   
ggplot2     ggplot2     /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 3.3.6   
glue        glue        /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.6.2   
gtable      gtable      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.3.1   
htmltools   htmltools   /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.5.3   
IRdisplay   IRdisplay   /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.1     
IRkernel    IRkernel    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.3     
isoband     isoband     /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.2.6   
jsonlite    jsonlite    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.8.2   
labeling    labeling    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.4.2   
lifecycle   lifecycle   /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.0.3   
magrittr    magrittr    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.0.3   
munsell     munsell     /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.5.0   
openxlsx    openxlsx    /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 4.2.5   
pbdZMQ      pbdZMQ      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 0.3-7   
pillar      pillar      /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 1.8.1   
pkgconfig   pkgconfig   /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.0.3   
R6          R6          /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.5.1   
⋮           ⋮           ⋮                                             ⋮       
zip         zip         /home/vivek/R/x86_64-pc-linux-gnu-library/4.2 2.2.1   
base        base        /usr/lib/R/library                            4.2.1   
boot        boot        /usr/lib/R/library                            1.3-28  
class       class       /usr/lib/R/library                            7.3-20  
cluster     cluster     /usr/lib/R/library                            2.1.4   
codetools   codetools   /usr/lib/R/library                            0.2-18  
compiler    compiler    /usr/lib/R/library                            4.2.1   
datasets    datasets    /usr/lib/R/library                            4.2.1   
foreign     foreign     /usr/lib/R/library                            0.8-82  
graphics    graphics    /usr/lib/R/library                            4.2.1   
grDevices   grDevices   /usr/lib/R/library                            4.2.1   
grid        grid        /usr/lib/R/library                            4.2.1   
KernSmooth  KernSmooth  /usr/lib/R/library                            2.23-20 
lattice     lattice     /usr/lib/R/library                            0.20-45 
MASS        MASS        /usr/lib/R/library                            7.3-58.1
Matrix      Matrix      /usr/lib/R/library                            1.5-1   
methods     methods     /usr/lib/R/library                            4.2.1   
mgcv        mgcv        /usr/lib/R/library                            1.8-40  
nlme        nlme        /usr/lib/R/library                    

### To remove a package on R

In [20]:
remove.packages("")

Removing package from ‘/home/vivek/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)



ERROR: Error in find.package(pkgs, lib): there is no package called ‘’


### First program on R

In [21]:
print("Hello world!!!")

[1] "Hello world!!!"


### Basic Arithmetic in R

In [22]:
12+45+9-7

[1] 59

### Complex Arithmetic in R

In [23]:
18+22/2-4/4*3.5

[1] 25.5

### Some important mathematical operators

In [25]:
sqrt(225) #Square root of the given number

[1] 15

#### abs() method in R programming is used to get the absolute value. i.e. a positive value doesn’t change and a negative value will be converted into a positive value.

In [26]:
abs(-3.17) #Absolute value of the given number

[1] 3.17

In [27]:
factorial(5) #Factorial of the given number

[1] 120

### Declaring variables in R

In [28]:
my_roll = 26

In [29]:
my_roll <- 26

In [30]:
my_roll

[1] 26

### Numeric Vector:

In [32]:
X<-1.5

### Constructing the numeric and character vectors in R

### Here we have to use a default function called Combine() or simply c()

In [33]:
c(10,20,20,30,40) #A Numerical/Integer vector

[1] 10 20 20 30 40

In [34]:
c('Hello2', 20, 'Hello4', 30) 

[1] "Hello2" "20"     "Hello4" "30"

In [35]:
c('Hello1', 'Hello2', 'Hello3') #A character vector

[1] "Hello1" "Hello2" "Hello3"

In [36]:
batch<-c("cdac","dbda", 2022)

In [37]:
typeof(batch)

[1] "character"

In [38]:
newbatch<-c(03,11,2022)

In [39]:
typeof(newbatch)

[1] "double"

In [40]:
newbatch<- c(03L,11L,2022L) #To read the double vector as an Integer

In [41]:
typeof(newbatch)

[1] "integer"

In [42]:
class(newbatch)

[1] "integer"

In [43]:
class()

ERROR: Error in class(): 0 arguments passed to 'class' which requires 1


In [44]:
c(1, 2, c(3, 4, 5))

[1] 1 2 3 4 5

In [45]:
y=c(1, 2, c(3, 4, 5),c(5,6,7))

In [46]:
y

[1] 1 2 3 4 5 5 6 7

In [47]:
Z = c(10:20,y, sum(10:20))

In [48]:
length(Z)

[1] 20

In [49]:
Z

[1]  10  11  12  13  14  15  16  17  18  19  20   1   2   3   4   5   5   6   7
[20] 165

### Creating the vector using (:) operator

In [50]:
1:15 #Generates numbers from 1 to 15

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [51]:
sum(1:15) #It sums the numbers from 1 to 15

[1] 120

In [52]:
a <- "hello" ## Assigning a string to variable a

In [53]:
a

[1] "hello"

In [55]:
b <- c("hello","there") ## Assigning two strings to variable b

In [56]:
b

[1] "hello" "there"

In [57]:
b[1] ## Printing first element of variable b

[1] "hello"

### Logical Vectors

In [58]:
1>2

[1] FALSE

In [59]:
c(1, 2) > 2

[1] FALSE FALSE

In [68]:
c(2, 3) > c(4, 4, 1, 3.5)

[1] FALSE FALSE  TRUE FALSE

In [61]:
c(2, 3) > c(1, 2, -1, 3, 5)

Warning message in c(2, 3) > c(1, 2, -1, 3, 5):
“longer object length is not a multiple of shorter object length”


[1]  TRUE  TRUE  TRUE FALSE FALSE

In [69]:
y=c(1, 2, c(3, 4, 5),c(5,6,7))

In [70]:
y

[1] 1 2 3 4 5 5 6 7

In [71]:
y == 5  # what will be the output?

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE

### Named Vectors

In [72]:
dbda <- c(janaki=1, nanda=2, madhavi=3, raghu=4 )

In [73]:
dbda
print(dbda)
show(dbda)

janaki   nanda madhavi   raghu 
      1       2       3       4

 janaki   nanda madhavi   raghu 
      1       2       3       4 
 janaki   nanda madhavi   raghu 
      1       2       3       4 


In [74]:
names(dbda) #print only names without values

[1] "janaki"  "nanda"   "madhavi" "raghu"

In [75]:
unname(dbda) #Print values without names

[1] 1 2 3 4

In [76]:
str(dbda) #See the structure of object ‘x’

 Named num [1:4] 1 2 3 4
 - attr(*, "names")= chr [1:4] "janaki" "nanda" "madhavi" "raghu"


In [77]:
dbda[order(dbda, decreasing = TRUE)]

raghu madhavi   nanda  janaki 
      4       3       2       1

In [78]:
table(is.na(dbda))


FALSE 
    4 

In [79]:
dbda[c(5)]<-NA

In [80]:
table(is.na(dbda))


FALSE  TRUE 
    4     1 

In [81]:
dbda

janaki   nanda madhavi   raghu         
      1       2       3       4      NA

### Extracting an element out of a vector

In [82]:
dbda[2]

nanda 
    2

In [83]:
dbda["nanda"]

nanda 
    2

In [84]:
dbda[["nanda"]]

[1] 2

### Extract elements which are greater than certain value

In [85]:
input <- c(21, 44, 69, 9, 12, 16, 19, 224, 261, 300)

In [86]:
input > 220 

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE

In [88]:
input1 <- input[input > 220]

In [89]:
input1

[1] 224 261 300

### Representation of Categorical Data

In [90]:
data<-c("lion","tiger","fox","wolf","tiger","wolf","lion","tiger","fox")
data

[1] "lion"  "tiger" "fox"   "wolf"  "tiger" "wolf"  "lion"  "tiger" "fox"

In [92]:
is.factor(data)

[1] FALSE

In [93]:
factor_data <- factor(data) 

In [94]:
factor_data 

[1] lion  tiger fox   wolf  tiger wolf  lion  tiger fox  
Levels: fox lion tiger wolf

#### Levels: It is a set of distinct values which are given to the input vector x.

In [ ]:
is.factor(factor_data)

### Data Frames

In [95]:
a<-c(1,2,3,4)
b<-c(2,4,6,8)

In [97]:
levels <- factor(c('A','B','B','A'))

In [98]:
MyDataFrame<-data.frame(a, b, levels)

In [99]:
MyDataFrame

a b levels
1 1 2 A     
2 2 4 B     
3 3 6 B     
4 4 8 A

### Class of Vectors

In [100]:
class(c(1, 2, 3))

[1] "numeric"

In [101]:
class(c(TRUE, TRUE, FALSE))

[1] "logical"

In [102]:
class(c('Hello', 'World'))

[1] "character"

In [104]:
class(MyDataFrame)

[1] "data.frame"

In [105]:
is.numeric(c(1, 2, 3))

[1] TRUE

In [106]:
is.numeric(c(TRUE, TRUE, FALSE))

[1] FALSE

In [107]:
is.numeric(c("Hello", "World"))

[1] FALSE

In [108]:
is.character(c('a','b','c'))

[1] TRUE

### Converting Vectors

In [109]:
strings <-c("1", "2", "3")
class(strings)

[1] "character"

In [110]:
strings + 10

ERROR: Error in parse(text = x, srcfile = src): <text>:1:10: unexpected input
1: strings + 
             ^


In [112]:
numbers = as.numeric(strings)

In [113]:
numbers

[1] 1 2 3

In [116]:
numbers*10 

[1] 10 20 30

In [117]:
as.numeric(c("1", "2", "3", "a"))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”


[1]  1  2  3 NA

In [118]:
as.logical(c(-1, 0, 1, 2))

[1]  TRUE FALSE  TRUE  TRUE

In [119]:
as.character(c(1, 2, 3))

[1] "1" "2" "3"

In [120]:
as.character(c(TRUE, FALSE))

[1] "TRUE"  "FALSE"

### Calling Fuctions in R

In [121]:
sum(10,20,30)

[1] 60

In [122]:
rep("Hello",3)

[1] "Hello" "Hello" "Hello"

In [123]:
sqrt(100)

[1] 10

In [125]:
substr("example",1,7)

[1] "example"

### Creating and using objects

In [126]:
myobj<-25+12/2-16+(7*pi/2)

In [127]:
myobj

[1] 25.99557

In [128]:
Myobj

ERROR: Error in eval(expr, envir, enclos): object 'Myobj' not found


In [129]:
x12 <- c(10,6,8)

In [130]:
x12

[1] 10  6  8

In [131]:
x12*3

[1] 30 18 24

### Using the c() command

In [132]:
a = (1:25)
b = (26:50)

In [133]:
d = c(a,b)

In [134]:
d

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

### Workspace in R

In [135]:
getwd()

[1] "/home/vivek"

In [136]:
ls()

[1] "a"           "b"           "batch"       "c"           "chars"      
 [6] "d"           "data"        "dbda"        "factor_data" "input"      
[11] "input1"      "levels"      "my_roll"     "MyDataFrame" "myobj"      
[16] "newbatch"    "number"      "numbers"     "strings"     "var"        
[21] "X"           "x12"         "y"           "yourname"    "Z"

In [137]:
objects()

[1] "a"           "b"           "batch"       "c"           "chars"      
 [6] "d"           "data"        "dbda"        "factor_data" "input"      
[11] "input1"      "levels"      "my_roll"     "MyDataFrame" "myobj"      
[16] "newbatch"    "number"      "numbers"     "strings"     "var"        
[21] "X"           "x12"         "y"           "yourname"    "Z"

In [140]:
d

ERROR: Error in eval(expr, envir, enclos): object 'd' not found


In [139]:
rm(d)

In [141]:
save(x12, file="Examples.rda")

In [142]:
save.image(file = "my_stuff.RData")

In [145]:
myname = "Vivek"
myname

[1] "Vivek"

In [146]:
save(yourname, file="myname.rda")

In [147]:
rm(yourname)

In [148]:
ls()

[1] "a"           "b"           "batch"       "c"           "chars"      
 [6] "data"        "dbda"        "factor_data" "input"       "input1"     
[11] "levels"      "my_roll"     "MyDataFrame" "myname"      "myobj"      
[16] "newbatch"    "number"      "numbers"     "strings"     "var"        
[21] "X"           "x12"         "y"           "Z"

In [149]:
load("myname.rda") #.rda stands for R Data File.

In [150]:
ls()

[1] "a"           "b"           "batch"       "c"           "chars"      
 [6] "data"        "dbda"        "factor_data" "input"       "input1"     
[11] "levels"      "my_roll"     "MyDataFrame" "myname"      "myobj"      
[16] "newbatch"    "number"      "numbers"     "strings"     "var"        
[21] "X"           "x12"         "y"           "yourname"    "Z"

### Accessing help and documentation in R

In [151]:
help(rm)

remove                  package:base                   R Documentation

_R_e_m_o_v_e _O_b_j_e_c_t_s _f_r_o_m _a _S_p_e_c_i_f_i_e_d _E_n_v_i_r_o_n_m_e_n_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘remove’ and ‘rm’ can be used to remove objects.  These can be
     specified successively as character strings, or in the character
     vector ‘list’, or through a combination of both.  All objects thus
     specified will be removed.

     If ‘envir’ is NULL then the currently active environment is
     searched first.

     If ‘inherits’ is ‘TRUE’ then parents of the supplied directory are
     searched until a variable with the given name is encountered.  A
     warning is printed for each variable that is not found.

_U_s_a_g_e:

     remove(..., list = character(), pos = -1,
            envir = as.environment(pos), inherits = FALSE)
     
     rm    (..., list = character(), pos = -1,
            envir = as.environment(pos), inherits = FALSE)
     
_A_r_g_u_m_e_n_t_s:

     ...: the objects to be removed, as names (unquoted) or character
          strings (quoted).

    list: a character vector naming objects to be removed.

     pos: where to do the removal.  By default, uses the current
          environment.  See ‘details’ for other possibilities.

   envir: the ‘environment’ to use.  See ‘details’.

inherits: should the enclosing frames of the environment be inspected?

_D_e_t_a_i_l_s:

     The ‘pos’ argument can specify the environment from which to
     remove the objects in any of several ways: as an integer (the
     position in the ‘search’ list); as the character string name of an
     element in the search list; or as an ‘environment’ (including
     using ‘sys.frame’ to access the currently active function calls).
     The ‘envir’ argument is an alternative way to specify an
     environment, but is primarily there for back compatibility.

     It is not allowed to remove variables from the base environment
     and base namespace, nor from any environment which is locked (see
     ‘lockEnvironment’).

     Earlier versions of R incorrectly claimed that supplying a
     character vector in ‘...’ removed the objects named in the
     character vector, but it removed the character vector.  Use the
     ‘list’ argument to specify objects _via_ a character vector.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘ls’, ‘objects’

_E_x_a_m_p_l_e_s:

     tmp <- 1:4
     ## work with tmp  and cleanup
     rm(tmp)
     
     ## Not run:
     
     ## remove (almost) everything in the working environment.
     ## You will get no warning, so don't do this unless you are really sure.
     rm(list = ls())
     ## End(Not run)

In [152]:
example(rm)

Warning message in source(tf, local, echo = echo, prompt.echo = paste0(prompt.prefix, :
“argument encoding="latin1" is ignored in MBCS locales”



rm> tmp <- 1:4

rm> ## work with tmp  and cleanup
rm> rm(tmp)

rm> ## Not run: 
rm> ##D ## remove (almost) everything in the working environment.
rm> ##D ## You will get no warning, so don't do this unless you are really sure.
rm> ##D rm(list = ls())
rm> ## End(Not run)
rm> 
rm> 


In [153]:
find.package("ggplot2")

[1] "/home/vivek/R/x86_64-pc-linux-gnu-library/4.2/ggplot2"

In [154]:
library(datasets) #Loads the datasets from library

In [155]:
data()

Data sets in package ‘AGD’:

boys7482                Growth of Dutch boys
cdc.bmi                 Reference tables from CDC 2000
cdc.hgt                 Reference tables from CDC 2000
cdc.wgt                 Reference tables from CDC 2000
nl3.bmi                 Reference tables from Third Dutch Growth Study
                        1980
nl4.bmi                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hdc                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hgt                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hip                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.lgl                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.shh                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.sit                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wfh                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wgt                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.whr                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wst                 Reference tables from Fourth Dutch Growth Study
                        1997
who.bmi                 References WHO
who.hdc                 References WHO
who.hgt                 References WHO
who.wfh                 References WHO
who.wfl                 References WHO
who.wgt                 References WHO
Data sets in package ‘datasets’:

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level of Lake Huron 1875-1972
LifeCycleSavings        Intercountry Life-Cycle Savings Data
Loblolly                Growth of Loblolly pine trees
Nile                    Flow of the River Nile
Orange                  Growth of Orange Trees
OrchardSprays           Potency of Orchard Sprays
PlantGrowth             Results from an Experiment on Plant Growth
Puromycin               Reaction Velocity of an Enzymatic Reaction
Seatbelts               Road Casualties in Great Britain 1969-84
Theoph                  Pharmacokinetics of Theophylline
Titanic                 Survival of passengers on the Titanic
ToothGrowth             The Effect of Vitamin C on Tooth Growth in
                        Guinea Pigs
UCBAdmissions           Student Admissions at UC Berkeley
UKDriverDeaths          Road Casualties in Great Britain 1969-84
UKgas                   UK Quarterly Gas Consumption
USAccDeaths             Accidental Deaths in the US 1973-1978
USArrests               Violent Crime Rates by US State
USJudgeRatings          Lawyers' Ratings of State Judges in the US
                        Superior Court
USPersonalExpenditure   Personal Expenditure Data
UScitiesD               Distances Between European Cities and Between
                        US Cities
VADeaths                Death Rates in Virginia (1940)
WWW

In [156]:
data(iris)

In [157]:
summary(iris)

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

In [158]:
summary(iris$Sepal.Length)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.300   5.100   5.800   5.843   6.400   7.900 

### Using Built-in Datasets in R

In [159]:
data(package = .packages(all.available = TRUE))
data(package='boot')

Data sets in package ‘AGD’:

boys7482                Growth of Dutch boys
cdc.bmi                 Reference tables from CDC 2000
cdc.hgt                 Reference tables from CDC 2000
cdc.wgt                 Reference tables from CDC 2000
nl3.bmi                 Reference tables from Third Dutch Growth Study
                        1980
nl4.bmi                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hdc                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hgt                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.hip                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.lgl                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.shh                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.sit                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wfh                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wgt                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.whr                 Reference tables from Fourth Dutch Growth Study
                        1997
nl4.wst                 Reference tables from Fourth Dutch Growth Study
                        1997
who.bmi                 References WHO
who.hdc                 References WHO
who.hgt                 References WHO
who.wfh                 References WHO
who.wfl                 References WHO
who.wgt                 References WHO
Data sets in package ‘boot’:

acme                    Monthly Excess Returns
aids                    Delay in AIDS Reporting in England and Wales
aircondit               Failures of Air-conditioning Equipment
aircondit7              Failures of Air-conditioning Equipment
amis                    Car Speeding and Warning Signs
aml                     Remission Times for Acute Myelogenous Leukaemia
beaver                  Beaver Body Temperature Data
bigcity                 Population of U.S. Cities
brambles                Spatial Location of Bramble Canes
breslow                 Smoking Deaths Among Doctors
calcium                 Calcium Uptake Data
cane                    Sugar-cane Disease Data
capability              Simulated Manufacturing Process Data
catsM                   Weight Data for Domestic Cats
cav                     Position of Muscle Caveolae
cd4                     CD4 Counts for HIV-Positive Patients
cd4.nested              Nested Bootstrap of cd4 data
channing                Channing House Data
city                    Population of U.S. Cities
claridge                Genetic Links to Left-handedness
cloth                   Number of Flaws in Cloth
co.transfer             Carbon Monoxide Transfer
coal                    Dates of Coal Mining Disasters
darwin                  Darwin's Plant Height Differences
dogs                    Cardiac Data for Domestic Dogs
downs.bc                Incidence of Down's Syndrome in British
                        Columbia
ducks                   Behavioral and Plumage Characteristics of
                        Hybrid Ducks
fir                     Counts of Balsam-fir Seedlings
frets                   Head Dimensions in Brothers
grav                    Acceleration Due to Gravity
gravity                 Acceleration Due to Gravity
hirose                  Failure Time of PET Film
islay                   Jura Quartzite Azimuths on Islay
manaus                  Average Heights of the Rio Negro river at
                        Manaus
melanoma                Survival from Malignant Melanoma
motor                   Data from a Simulated Motorcycle Accident
neuro                   Neurophysiological Point Process Data
nitrofen                Toxicity of Nitrofen in Aquatic Systems
nodal                   Nodal Involvement in Prost

### Data Structures in R-Integer Vectors

In [160]:
seq(4,9)

[1] 4 5 6 7 8 9

In [161]:
seq(4,10,2)

[1]  4  6  8 10

In [162]:
seq(1.65,1.90,0.05)

[1] 1.65 1.70 1.75 1.80 1.85 1.90

In [164]:
seq(1,6,length.out = 5) #Here, length.out is defining how many elements we want From to To numbers

[1] 1.00 2.25 3.50 4.75 6.00

In [165]:
rep("DBDA", 4)

[1] "DBDA" "DBDA" "DBDA" "DBDA"

In [166]:
oops <- c(7,9,13)

In [167]:
rep(oops,3)

[1]  7  9 13  7  9 13  7  9 13

In [168]:
rep(oops,1:3)

[1]  7  9  9 13 13 13

In [169]:
rep(oops,1:4)

ERROR: Error in rep(oops, 1:4): invalid 'times' argument


In [170]:
rep(1:2,c(10,15))

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2

In [171]:
rep(1:2,each=10)

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2

In [172]:
rep(1:2,c(10,2)

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: rep(1:2,c(10,2)
   ^


### Integer vectors : Indexing

In [173]:
a = (1:100)

In [174]:
length(a)

[1] 100

In [175]:
a[1]

[1] 1

In [176]:
a[25]

[1] 25

In [177]:
a[98]

[1] 98

In [178]:
a[-1:-99]

[1] 100

In [179]:
a[-1:-95]

[1]  96  97  98  99 100

In [180]:
a[1:15]

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [181]:
a[c(1:5,55:73)]

[1]  1  2  3  4  5 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73

### Character Vector

In [182]:
c("Huey","Dewey","Louie")

[1] "Huey"  "Dewey" "Louie"

In [183]:
c('Huey','Dewey','Louie')

[1] "Huey"  "Dewey" "Louie"

In [184]:
cat(c("Huey","Dewey","Louie"))

Huey Dewey Louie

In [185]:
cat("What is \"R\"?\n")

What is "R"?


In [186]:
c("Apple",F,"Orange",T)

[1] "Apple"  "FALSE"  "Orange" "TRUE"

In [187]:
c("Apple","F","Orange","T")

[1] "Apple"  "F"      "Orange" "T"

In [ ]:
names = c("Huey","Dewey","Louie")

### Example of Character Vector: Indexing

In [199]:
e = c("Huey","Dewey","Louie","Kaduba")

In [200]:
e[1]

[1] "Huey"

In [201]:
e[2]

[1] "Dewey"

In [202]:
e[3]

[1] "Louie"

In [204]:
e[-2:-3]

[1] "Huey"   "Kaduba"

In [205]:
e[-2]

[1] "Huey"   "Louie"  "Kaduba"

In [206]:
f = c("aa","bb","cc","dd","ee","ff")

In [194]:
f[1:4]

[1] "aa" "bb" "cc" "dd"

In [195]:
f[3:5]

[1] "cc" "dd" "ee"

In [196]:
f[1,2,3]

ERROR: Error in f[1, 2, 3]: incorrect number of dimensions


In [207]:
f(c[1,2,3])

ERROR: Error in f(c[1, 2, 3]): could not find function "f"


### Combination of Int and Char

In [208]:
anow = c(1,2,3)

In [209]:
bnow = c(4,5,6,'CDAC','DBDA')

In [210]:
cnow = c(7,8,9,'E-City','NA')

In [211]:
full = c(anow,bnow,cnow)

In [212]:
full

[1] "1"      "2"      "3"      "4"      "5"      "6"      "CDAC"   "DBDA"  
 [9] "7"      "8"      "9"      "E-City" "NA"

In [213]:
xnow = c(blood = "Red", sky = 'Blue', coal = 'Black')

In [214]:
xnow

blood     sky    coal 
  "Red"  "Blue" "Black"

### Matrix : Using dim() keyword

In [220]:
x <- 1:12

In [221]:
dim(x) = c(3,4)

In [222]:
x

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [223]:
dim(x) = c(4,4)

ERROR: Error in dim(x) = c(4, 4): dims [product 16] do not match the length of object [12]


### Matrix : Using Matrix() keyword

In [224]:
matrix(1:16,nrow = 4, ncol = 4, byrow = FALSE)

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [225]:
matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

### Creating Matrix using Vectors

In [226]:
cbind(A = 1:5, B = 6:10, D = 11:15)

A B  D 
[1,] 1  6 11
[2,] 2  7 12
[3,] 3  8 13
[4,] 4  9 14
[5,] 5 10 15

In [227]:
rbind(a = 1:3, b = 4:6, c = 7:9)

[,1] [,2] [,3]
a 1    2    3   
b 4    5    6   
c 7    8    9

In [228]:
help(array)

array                   package:base                   R Documentation

_M_u_l_t_i-_w_a_y _A_r_r_a_y_s

_D_e_s_c_r_i_p_t_i_o_n:

     Creates or tests for arrays.

_U_s_a_g_e:

     array(data = NA, dim = length(data), dimnames = NULL)
     as.array(x, ...)
     is.array(x)
     
_A_r_g_u_m_e_n_t_s:

    data: a vector (including a list or ‘expression’ vector) giving
          data to fill the array.  Non-atomic classed objects are
          coerced by ‘as.vector’.

     dim: the dim attribute for the array to be created, that is an
          integer vector of length one or more giving the maximal
          indices in each dimension.

dimnames: either ‘NULL’ or the names for the dimensions.  This must be
          a list (or it will be ignored) with one component for each
          dimension, either ‘NULL’ or a character vector of the length
          given by ‘dim’ for that dimension.  The list can be named,
          and the list names will be used as names for the dimensions.
          If the list is shorter than the number of dimensions, it is
          extended by ‘NULL’s to the length required.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

_D_e_t_a_i_l_s:

     An array in R can have one, two or more dimensions.  It is simply
     a vector which is stored with additional attributes giving the
     dimensions (attribute ‘"dim"’) and optionally names for those
     dimensions (attribute ‘"dimnames"’).

     A two-dimensional array is the same thing as a ‘matrix’.

     One-dimensional arrays often look like vectors, but may be handled
     differently by some functions: ‘str’ does distinguish them in
     recent versions of R.

     The ‘"dim"’ attribute is an integer vector of length one or more
     containing non-negative values: the product of the values must
     match the length of the array.

     The ‘"dimnames"’ attribute is optional: if present it is a list
     with one component for each dimension, either ‘NULL’ or a
     character vector of the length given by the element of the ‘"dim"’
     attribute for that dimension.

     ‘is.array’ is a primitive function.

     For a list array, the ‘print’ methods prints entries of length not
     one in the form ‘integer,7’ indicating the type and length.

_V_a_l_u_e:

     ‘array’ returns an array with the extents specified in ‘dim’ and
     naming information in ‘dimnames’.  The values in ‘data’ are taken
     to be those in the array with the leftmost subscript moving
     fastest.  If there are too few elements in ‘data’ to fill the
     array, then the elements in ‘data’ are recycled.  If ‘data’ has
     length zero, ‘NA’ of an appropriate type is used for atomic
     vectors (‘0’ for raw vectors) and ‘NULL’ for lists.

     Unlike ‘matrix’, ‘array’ does not currently remove any attributes
     left by ‘as.vector’ from a classed list ‘data’, so can return a
     list array with a class attribute.

     ‘as.array’ is a generic function for coercing to arrays.  The
     default method does so by attaching a ‘dim’ attribute to it.  It
     also attaches ‘dimnames’ if ‘x’ has ‘names’.  The sole purpose of
     this is to make it possible to access the ‘dim[names]’ attribute
     at a later time.

     ‘is.array’ returns ‘TRUE’ or ‘FALSE’ depending on whether its
     argument is an array (i.e., has a ‘dim’ attribute of positive
     length) or not.  It is generic: you can write methods to handle
     specific classes of objects, see InternalMethods.

_N_o_t_e:

     ‘is.array’ is a primitive function.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘aperm’, ‘matrix’, ‘dim’, ‘dimnames’.

_E_x_a_m_p_l_e_s:

     dim(as.array(letters))
     array(1:3, c(2,4)) # recycle 1:3 "2 2/3 times"
     #     [,1] [,2] [,3] [,4]
     #[1,]    1    3

### Subsetting a matrix : Extracting the elements of Matrix

In [229]:
X = matrix(c(1,3,5,7,9,11,13,15,17), ncol = 3)

In [230]:
X

[,1] [,2] [,3]
[1,] 1     7   13  
[2,] 3     9   15  
[3,] 5    11   17

In [231]:
X[1,2]

[1] 7

In [232]:
X[3,3]

[1] 17

In [233]:
X[3,1]

[1] 5

### Matrix Operation

In [234]:
X = matrix(c(1,3,5,7,9,11,13,15,17), ncol = 3)
X

[,1] [,2] [,3]
[1,] 1     7   13  
[2,] 3     9   15  
[3,] 5    11   17

In [235]:
Y = matrix(c(2,4,6,8,10,12,14,16,18), ncol = 3)
Y

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [236]:
X+Y #Addition of two matrices

[,1] [,2] [,3]
[1,]  3   15   27  
[2,]  7   19   31  
[3,] 11   23   35

In [237]:
Y-X #Subtraction of Matrices

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

In [238]:
X*Y

[,1] [,2] [,3]
[1,]  2    56  182 
[2,] 12    90  240 
[3,] 30   132  306

In [239]:
rowSums(X)

[1] 21 27 33

In [240]:
rowMeans(Y)

[1]  8 10 12

In [241]:
colSums(Y)

[1] 12 30 48

In [242]:
colMeans(Y)

[1]  4 10 16

### Arrays

In [243]:
array(c(0:9), dim = c(1,5,1))

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    1    2    3    4

In [244]:
array(c(0:9), dim = c(2,5,2))

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    2    4    6    8
[2,]    1    3    5    7    9

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    2    4    6    8
[2,]    1    3    5    7    9

#### How does dim=c(2,5,2) work?
The first and second number in the bracket specifies the amount of rows and columns.

The last number in the bracket specifies how many dimensions we want.



In [246]:
thisarray <- c(1:24)

In [247]:
multiarray <- array(thisarray, dim = c(4, 3, 2))

In [248]:
print(multiarray)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



### Lists

In [249]:
lst = list(c(1:15))

In [250]:
lst[]

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [251]:
l = c(2,3,5)

In [252]:
l

[1] 2 3 5

In [253]:
m = c("aa","bb","cc","dd","ee","ff")

In [254]:
m

[1] "aa" "bb" "cc" "dd" "ee" "ff"

In [255]:
n = c(TRUE, FALSE, TRUE, TRUE, FALSE)

In [256]:
n

[1]  TRUE FALSE  TRUE  TRUE FALSE

In [257]:
lst1 = list(l,m,n,3)

In [258]:
lst1

[[1]]
[1] 2 3 5

[[2]]
[1] "aa" "bb" "cc" "dd" "ee" "ff"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[4]]
[1] 3

### Accessing list elements

In [259]:
lst2 = list(x = 1, y = c(FALSE, TRUE), z = c('a','b','c','d'))

In [260]:
lst2$x

[1] 1

In [261]:
lst2$y

[1] FALSE  TRUE

In [262]:
lst2$z

[1] "a" "b" "c" "d"

### Data-Frames

In [263]:
d = c(1:4)

In [264]:
e = c('red','white','red',NA)

In [265]:
f = c(TRUE,TRUE,TRUE,FALSE)

In [266]:
mydf = data.frame(d,e,f)

In [267]:
mydf

d e     f    
1 1 red    TRUE
2 2 white  TRUE
3 3 red    TRUE
4 4 NA    FALSE

In [268]:
names(mydf) = c("ID","COLOR","QA-TEST")

In [269]:
mydf

ID COLOR QA-TEST
1 1  red    TRUE  
2 2  white  TRUE  
3 3  red    TRUE  
4 4  NA    FALSE

In [270]:
mydf[1:2]

ID COLOR
1 1  red  
2 2  white
3 3  red  
4 4  NA

In [271]:
mydf[2:3]

COLOR QA-TEST
1 red    TRUE  
2 white  TRUE  
3 red    TRUE  
4 NA    FALSE

In [272]:
mydf$ID

[1] 1 2 3 4

In [273]:
mydf$COLOR

[1] "red"   "white" "red"   NA

In [274]:
mydf[1,2:3]

COLOR QA-TEST
1 red   TRUE

In [275]:
mydf[4,2:3]

COLOR QA-TEST
4 NA    FALSE

In [276]:
mydf[3,]

ID COLOR QA-TEST
3 3  red   TRUE

In [277]:
mydf[,3]

[1]  TRUE  TRUE  TRUE FALSE

In [278]:
dim(mtcars)

[1] 32 11

In [279]:
(mtcars)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [280]:
dim()

ERROR: Error in dim(): 0 arguments passed to 'dim' which requires 1


In [281]:
affordable_cars <- subset(mtcars, mpg >= 20 & hp >= 90)

In [282]:
affordable_cars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
v <- c(1,9,3,7,20,5,12,78,10,4,6)

In [ ]:
subset(v,v>5)

In [ ]:
v[v<5]

In [ ]:
t = c('one','two','three','four','five','six')

In [ ]:
subset(t,t!='one')

### Reading and getting data in R

In [ ]:
read.csv('../vivek/NLP_ipynb/POS_NEW/stack-overflow-developer-survey-2019/survey_results_public.csv')

In [ ]:
myData = read.delim("thoughts1.txt", header = FALSE)
print(myData)

### Using c() command

In [ ]:
ab = c(123,456,789,321,654,987)

In [ ]:
ab

In [ ]:
bc = c(12,23,34,45,56,78,89,90)

In [ ]:
cd = c(1,11,111,1111,ab,bc)

In [ ]:
cd

In [ ]:
cd = c(cd,01,02,03,04,05,06)

In [ ]:
cd

In [ ]:
cd = c(cd,'Bangalore','Mumbai','Kolkata','Delhi')

In [ ]:
cd

In [ ]:
c(1L,2L,3L,'APPLE','BANANA')

### Using Scan() and Readline() command

In [ ]:
myName = readline()

In [ ]:
myName

In [ ]:
typeof(myName)

In [ ]:
a = as.numeric(readline())
b = as.numeric(readline())
c = a + b
c

In [ ]:
readdata <- scan('../vivek/thoughts1.txt',what = 'text')

In [ ]:
readdata

In [ ]:
dir()

In [ ]:
scan(file.choose())

In [ ]:
read.fwf('students.txt',widths = (c(12,30)))

### Importing Excel Spreadsheet in R

In [ ]:
install.packages('openxlsx')

In [ ]:
library(openxlsx)

In [ ]:
read.xlsx('../vivek/sample.xlsx')

In [ ]:
library(datasets)

In [ ]:
data(HairEyeColor)

In [ ]:
HairEyeColor

In [ ]:
write.csv(HairEyeColor,'haireyecolor.csv')